import React from "react";
import Link from "next/link";
import { Shield } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white md:bg-[#F8F9FB] dark:bg-slate-900 dark:md:bg-[#0f172a] text-gray-900 dark:text-gray-300 transition-colors duration-300 flex flex-col font-sans">
      <Navbar />
      <main className="flex-grow py-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
        <div className="mb-12 text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 dark:text-white mb-4 tracking-tight">Privacy Policy</h1>
          <p className="text-slate-600 dark:text-slate-400">Last updated: July 2026</p>
        </div>

        <div className="space-y-12 prose dark:prose-invert prose-indigo max-w-none text-slate-700 dark:text-slate-300">
          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">1. Introduction</h2>
            <p className="leading-relaxed">
              Welcome to RelayPost. This policy explains what information we collect and how we use it. By using RelayPost, you agree to the practices described below.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">2. Information We Collect</h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-600 dark:text-slate-400">
              <li><strong>Account information:</strong> Name, and email address when you register.</li>
              <li><strong>Usage data:</strong> Basic information about how you interact with articles and features, used to improve the platform.</li>
              <li><strong>Payment information:</strong> If you make a contribution, payment is processed directly by Razorpay. We do not store your card, UPI, or bank details — we only receive a transaction reference and status.</li>
              <li><strong>AI feature queries:</strong> If you use AI-powered features (summaries, Ask AI), your questions and the generated responses may be logged to improve accuracy and prevent misuse.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">3. How We Use Your Information</h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-600 dark:text-slate-400">
              <li>To create and manage your account</li>
              <li>To process contributions via Razorpay</li>
              <li>To operate and improve AI features and the platform generally</li>
              <li>To respond to support requests</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">4. Sharing Your Information</h2>
            <p className="leading-relaxed">
              We do not sell your personal data. We only share information with Razorpay (for payment processing) and service providers who help us run the platform, or where required by law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">5. AI-Generated Content</h2>
            <p className="leading-relaxed">
              Summaries and responses generated by AI may occasionally be inaccurate or incomplete. Please verify important information against original sources where possible.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">6. Data Security</h2>
            <p className="leading-relaxed">
              We take reasonable measures to protect your information.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">7. Children</h2>
            <p className="leading-relaxed">
You must have attained the age of majority to be able to use and access our Services. If you are a minor in your jurisdiction, your registration and use of our Services must be with the supervision of an adult.            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">8. Changes to This Policy</h2>
            <p className="leading-relaxed">
              We may update this policy as the platform evolves. Continued use after changes means you accept the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white mb-4">9. Contact Us</h2>
            <p className="leading-relaxed">
              Questions? Email us at kartikkalra2705@gmail.com or visit our <Link href="/contact" className="text-indigo-400 hover:text-indigo-300 transition-colors underline underline-offset-4">Contact Page</Link>.
            </p>
          </section>
        </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
